###
GET http://127.0.0.1:8000/api/manage/collect/list

###
GET http://127.0.0.1:8000/api/manage/collect/options

###
GET http://127.0.0.1:8000/api/manage/collect/find?id=47a1453218ad027f

###
GET http://127.0.0.1:8000/api/index

###
http://127.0.0.1:8000/api/filmClassify?pid=0

###
http://127.0.0.1:8000/api/filmDetail?id=62662