### 失效记录
GET {{url}}/api/manage/collect/record/list?originId=&collectType=-1&status=-1&betweenTime=&endTime=&current=1&pageSize=10

###
GET {{url}}/api/manage/collect/options

###
GET {{url}}/api/manage/collect/find?id=47a1453218ad027f


###
GET {{url}}/api/manage/collect/list

### 采集测试
POST {{url}}/api/manage/collect/test
Content-Type: application/json

{
  "resultModel": 0,
  "id": "ca0090b9c9ff7dfd",
  "syncPictures": false,
  "type_id": 30,
  "interval": 0,
  "grade": 0,
  "name": "HD(LZ)",
  "uri": "https://cj.lziapi.com/api.php/provide/vod/",
  "collectType": 0,
  "state": true
}

###
POST {{url}}/api/manage/spider/start
Content-Type: application/json

{
  "id": "ca0090b9c9ff7dfd",
  "time": 24,
  "batch": false
}