PRIVATE_KEY = '''-----BEGIN RSA PRIVATE KEY-----\nMIIBPAIBAAJBANNnshoUaT2gFNrihmFdmC1cBCs1XLFc5Fn3MfNOR3aOGDO0ohXl\nbku6Ir/qITN/yeH5pY34WEcETet3YhESpE8CAwEAAQJBAI7Ekdfg/u26RTtJDd2F\nWrcPVFVl1TKGfERxl08sB0D9HLvUSBfAEg/UpfWSQ57aSJ9b0gVKmDhgF8FymuUV\nv2kCIQDzXXSZ/oeKmqObwad0Fa82IFof3LeZdpbrjyz3w45JDQIhAN5hdmuW+y2w\nUgSy0o4zGFsEG/RBZsvVnSSfkdR47dPLAiEA2XbPNLQu5fnc7NeVDLQ7xsAOCJ6w\nKR/BKGjeI9/JCxkCIQCjMkU0ec2FXxMhzZXFs2uZR6+4FdL5nZ9ABDaCBekK9wIg\nXEfd11qabi9jPrbsOVNZCTk51B7Ug0ZwGyn0BA8Jlo0=\n-----END RSA PRIVATE KEY-----\n'''

PUBLIC_KEY = '''-----BEGIN RSA PUBLIC KEY-----\nMEgCQQDTZ7IaFGk9oBTa4oZhXZgtXAQrNVyxXORZ9zHzTkd2jhgztKIV5W5LuiK/\n6iEzf8nh+aWN+FhHBE3rd2IREqRPAgMBAAE=\n-----END RSA PUBLIC KEY-----\n'''

ISSUER = "GoFilm"
AUTH_TOKEN_EXPIRES = 10 * 24  # 单位：小时
USER_TOKEN_KEY = "User:Token:%d"