from typing import Optional, List, Any
from sqlmodel import SQLModel, Field


class MacVod(SQLModel, table=True):
    __tablename__ = "mac_vod"
    vod_id: int = Field(primary_key=True, description="影片ID")
    type_id: int = Field(description="分类ID")
    type_id_1: int = Field(description="一级分类ID")
    group_id: int = Field(description="用户组ID")
    vod_name: str = Field(description="影片名称")
    vod_sub: Optional[str] = Field(default=None, description="影片别名")
    vod_en: Optional[str] = Field(default=None, description="影片名中文拼音")
    vod_status: int = Field(description="影片状态")
    vod_letter: Optional[str] = Field(default=None, description="影片名首字母(大写)")
    vod_color: Optional[str] = Field(default=None, description="UI展示颜色")
    vod_tag: Optional[str] = Field(default=None, description="索引标签")
    vod_class: Optional[str] = Field(default=None, description="剧情分类标签")
    vod_pic: Optional[str] = Field(default=None, description="影片封面图")
    vod_pic_thumb: Optional[str] = Field(default=None, description="缩略图")
    vod_pic_slide: Optional[str] = Field(default=None, description="幻灯图片")
    vod_pic_screenshot: Optional[str] = Field(default=None, description="截图")
    vod_actor: Optional[str] = Field(default=None, description="演员名")
    vod_director: Optional[str] = Field(default=None, description="导演")
    vod_writer: Optional[str] = Field(default=None, description="作者")
    vod_behind: Optional[str] = Field(default=None, description="幕后")
    vod_blurb: Optional[str] = Field(default=None, description="内容简介")
    vod_remarks: Optional[str] = Field(default=None, description="更新状态 (完结/更新xx集)")
    vod_pub_date: Optional[str] = Field(default=None, description="上映日期")
    vod_total: Optional[int] = Field(default=None, description="总集数")
    vod_serial: Optional[str] = Field(default=None, description="连载数")
    vod_tv: Optional[str] = Field(default=None, description="上映电视台")
    vod_weekday: Optional[str] = Field(default=None, description="节目周期")
    vod_area: Optional[str] = Field(default=None, description="地区")
    vod_lang: Optional[str] = Field(default=None, description="语言")
    vod_year: Optional[str] = Field(default=None, description="年代")
    vod_version: Optional[str] = Field(default=None, description="画质版本")
    vod_state: Optional[str] = Field(default=None, description="影片类别")
    vod_author: Optional[str] = Field(default=None, description="编辑人员")
    vod_jump_url: Optional[str] = Field(default=None, description="跳转url")
    vod_tpl: Optional[str] = Field(default=None, description="独立模板")
    vod_tpl_play: Optional[str] = Field(default=None, description="独立播放页模板")
    vod_tpl_down: Optional[str] = Field(default=None, description="独立下载页模板")
    vod_is_end: Optional[int] = Field(default=None, description="是否完结")
    vod_lock: Optional[int] = Field(default=None, description="锁定")
    vod_level: Optional[int] = Field(default=None, description="推荐级别")
    vod_copyright: Optional[int] = Field(default=None, description="版权")
    vod_points: Optional[int] = Field(default=None, description="积分")
    vod_points_play: Optional[int] = Field(default=None, description="点播付费")
    vod_points_down: Optional[int] = Field(default=None, description="下载付费")
    vod_hits: Optional[int] = Field(default=None, description="总点击量")
    vod_hits_day: Optional[int] = Field(default=None, description="日点击量")
    vod_hits_week: Optional[int] = Field(default=None, description="周点击量")
    vod_hits_month: Optional[int] = Field(default=None, description="月点击量")
    vod_duration: Optional[str] = Field(default=None, description="时长")
    vod_up: Optional[int] = Field(default=None, description="顶数")
    vod_down: Optional[int] = Field(default=None, description="踩数")
    vod_score: Optional[str] = Field(default=None, description="平均分")
    vod_score_all: Optional[int] = Field(default=None, description="总评分")
    vod_score_num: Optional[int] = Field(default=None, description="评分次数")
    vod_time: Optional[str] = Field(default=None, description="更新时间")
    vod_time_add: Optional[int] = Field(default=None, description="添加时间")
    vod_time_hits: Optional[int] = Field(default=None, description="点击时间")
    vod_time_make: Optional[int] = Field(default=None, description="生成时间")
    vod_trysee: Optional[int] = Field(default=None, description="试看时长")
    vod_douban_id: Optional[int] = Field(default=None, description="豆瓣ID")
    vod_douban_score: Optional[str] = Field(default=None, description="豆瓣评分")
    vod_reurl: Optional[str] = Field(default=None, description="来源地址")
    vod_rel_vod: Optional[str] = Field(default=None, description="关联视频ids")
    vod_rel_art: Optional[str] = Field(default=None, description="关联文章ids")
    vod_pwd: Optional[str] = Field(default=None, description="访问内容密码")
    vod_pwd_url: Optional[str] = Field(default=None, description="访问密码连接")
    vod_pwd_play: Optional[str] = Field(default=None, description="访问播放页密码")
    vod_pwd_play_url: Optional[str] = Field(default=None, description="获取访问密码连接")
    vod_pwd_down: Optional[str] = Field(default=None, description="访问下载页密码")
    vod_pwd_down_url: Optional[str] = Field(default=None, description="获取下载密码连接")
    vod_content: Optional[str] = Field(default=None, description="详细介绍")
    vod_play_from: Optional[str] = Field(default=None, description="播放组")
    vod_play_server: Optional[str] = Field(default=None, description="播放组服务器")
    vod_play_note: Optional[str] = Field(default=None, description="播放组备注")
    vod_play_url: Optional[str] = Field(default=None, description="播放地址")
    vod_down_from: Optional[str] = Field(default=None, description="下载组")
    vod_down_server: Optional[str] = Field(default=None, description="下载服务器组")
    vod_down_note: Optional[str] = Field(default=None, description="下载备注")
    vod_down_url: Optional[str] = Field(default=None, description="下载地址")
    vod_plot: Optional[int] = Field(default=None, description="是否包含分级剧情")
    vod_plot_name: Optional[str] = Field(default=None, description="分类剧情名称")
    vod_plot_detail: Optional[str] = Field(default=None, description="分集剧情详情")
    type_name: Optional[str] = Field(default=None, description="分类名称")


class FilmDetailLPage(SQLModel):
    code: int
    msg: str
    page: Any
    pagecount: int
    limit: Any
    total: int
    list: List[MacVod]
