### 新增或更新 AnimeVod 接口测试
POST http://localhost:8000/api/anime/upsert
Content-Type: application/json

{
  "vod_id": 14491,
  "name": "石纪元",
  "vod_pic": "https://assets.anixplayer.net/image/poster/medium/14491-455b14c5518261c3acce26183bbe5053.jpg",
  "episode": 111,
  "url": "https://vip.dytt-cine.com/20250911/55633_e81b2424/index.m3u8"
}

### 新增或更新 AnimeVod 接口测试 - 不同 host
POST http://localhost:8000/api/anime/upsert
Content-Type: application/json

{
  "name": "鬼灭之刃",
  "episode": "1",
  "url": "https://backup.example.com/demon-slayer/ep1.mp4"
}

### 根据 name 和 episode 查询 AnimeVod 测试
POST http://localhost:8000/api/anime/search
Content-Type: application/json

{
  "name": "鬼灭之刃",
  "episode": "1"
}

### 测试不存在的动漫
POST http://localhost:8000/api/anime/search
Content-Type: application/json

{
  "name": "石纪元 新世界 第2部分",
  "episode": "7"
}

### 测试不存在的集数
POST http://localhost:8000/api/anime/search
Content-Type: application/json

{
  "name": "石纪元 新世界 第2部分"
}



### 创建 AnimeVod 记录
POST http://localhost:8000/api/anime/
Content-Type: application/json

{
  "vod_name": "测试动漫",
  "vod_play_url": {
    "host1": {
      "episode1": "http://example.com/episode1.mp4",
      "episode2": "http://example.com/episode2.mp4"
    },
    "host2": {
      "episode1": "http://anotherhost.com/episode1.mp4"
    }
  }
}

> {%
client.global.set("vod_id", response.body.data.vod_id);
%}

### 获取所有 AnimeVod 记录
GET http://localhost:8000/api/anime/?offset=1&limit=1

### 获取所有 AnimeVod 记录
POST http://localhost:8000/api/anime/page
Content-Type: application/json

{
  "page_num": 1,
  "page_size": 10
}

### 根据 ID 获取单个 AnimeVod 记录
GET http://localhost:8000/api/anime/{{vod_id}}

### 更新 AnimeVod 记录
PUT http://localhost:8000/api/anime/{{vod_id}}
Content-Type: application/json

{
  "vod_name": "更新后的动漫名称",
  "vod_play_url": {
    "host1": {
      "episode1": "http://example.com/new_episode1.mp4"
    }
  }
}

### 删除 AnimeVod 记录
DELETE http://localhost:8000/api/anime/{{vod_id}}

###

GET http://localhost:8000/proxy/api/v2/comment/192480001?withRelated=true&chConvert=1
