/*
    film_source init
*/
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('8d5d4e3b372b5229', '天涯资源', 'https://tyyszy.com/api.php/provide/vod', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('f17ee9f6412a4e2f', '如意资源', 'https://cj.rycjapi.com/api.php/provide/vod', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', 30, 't', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('d2b91ef26aaf43cd', 'jkun资源', 'https://jkunzyapi.com/api.php/provide/vod', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 't', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('98f87b06d7dce304', '黄色仓库', 'https://hsckzy.vip/api.php/provide/vod/at/json', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', 39, 't', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('159cb472ecd966e9', '魔都资源', 'https://www.mdzyapi.com/api.php/provide/vod', 'JsonResult', 'MasterCollect', 'f', 'CollectVideo', 6, 't', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('ca0090b9c9ff7dfd', 'HD(LZ)', 'https://cj.lziapi.com/api.php/provide/vod/', 'JsonResult', 'MasterCollect', 'f', 'CollectVideo', 30, 't', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('bb108f0b8b605bc0', 'HD(BF)', 'https://bfzyapi.com/api.php/provide/vod/', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 2500);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('1d40c3d70fbcd0ef', 'HD(FF)', 'http://cj.ffzyapi.com/api.php/provide/vod/', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('8bffcc40f80e43d1', 'HD(OK)', 'https://okzyapi.com/api.php/provide/vod/', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('0a371252a976943f', 'HD(HM)', 'https://json.heimuer.xyz/api.php/provide/vod/', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('8cb4cc755c776395', 'HD(LY)', 'https://360zy.com/api.php/provide/vod/at/json', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('b3190995acfd36ad', 'HD(SN)', 'https://suoniapi.com/api.php/provide/vod/from/snm3u8/', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 2000);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('c6b3ac6a324e67b2', 'HD(DB)', 'https://caiji.dbzy.tv/api.php/provide/vod/from/dbm3u8/at/josn/', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 0);
INSERT INTO "public"."film_source" ("id", "name", "uri", "resultModel", "grade", "syncPictures", "collectType", "type_id", "state", "interval") VALUES ('f0d29b64874bfc48', 'HD(IK)', 'https://ikunzyapi.com/api.php/provide/vod/at/json', 'JsonResult', 'SlaveCollect', 'f', 'CollectVideo', -1, 'f', 0);

